---
- name: Execute current version check - run validate version module
  validate_version:
    version: "{{ pumpkin_version }}"
  register: module_result
  delegate_to: localhost

- name: Process current version check details
  set_fact:
    check_details: "{{ module_result.check_details }}"
    check_errors: "{{ module_result.check_errors | default(none) }}"