---

- name: Run upgrade path verification module
  is_upgrade_path_valid:
    current_version: "{{ pumpkin_version }}"
    target_version: "{{ version | default(omit) }}"
  register: module_result
  delegate_to: localhost

- name: Process upgrade path check details
  set_fact:
    check_details: "{{ module_result.check_details }}"
    check_errors: "{{ module_result.check_errors | default(none) }}"
    check_skipped: "{{ module_result.check_skipped | default(none) }}"
