[local]
localhost ansible_connection=local tasks_path=tasks

[remote]
remote_host ansible_connection=ssh ansible_host=10.45.96.116 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ulis-dev-rnd.pem tasks_path=tasks
saggi_host ansible_connection=ssh ansible_host=10.45.80.8 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ulis-dev-rnd.pem tasks_path=tasks
not_existent ansible_connection=ssh ansible_host=10.11.12.13 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ulis-dev-rnd.pem tasks_path=tasks
