---

- name: Prepare host aggregation variables - issue details and whether was skipped
  set_fact:
    _host_issues: "{{ (hostvars[aggregated_host].host_results['Counts - Issues'] | default({})) }}"
    _host_has_skipped: "{{ (hostvars[aggregated_host].host_results['Counts - Skipped'] | default(0)) | int > 0 }}"


- name: Prepare host aggregation variables - whether has issues
  set_fact:
    _host_has_issues: "{{ _host_issues | length > 0 }}"


- name: Prepare host aggregation variables - whether is clean (no issues and not skipped)
  set_fact:
    _host_is_clean: "{{ not _host_has_issues and not _host_has_skipped }}"


- name: Aggregate skipped / clean host counters
  set_fact:
    overall_results: >-
      {{
        overall_results | combine({
          'Counts - Skipped': overall_results['Counts - Skipped'] + (1 if _host_has_skipped else 0),
          'Counts - no Issues': overall_results['Counts - no Issues'] + (1 if _host_is_clean else 0),
          'Hosts with Skipped': overall_results['Hosts with Skipped'] + ([aggregated_host] if _host_has_skipped else []),
          'Hosts with no Issues': overall_results['Hosts with no Issues'] + ([aggregated_host] if _host_is_clean else [])
        }, recursive=True)
      }}

- name: Aggregate issue counts and host lists per severity
  set_fact:
    overall_results: >-
      {{
        overall_results | combine({
          'Counts - Issues':
            overall_results['Counts - Issues']
            | combine({
                severity: (overall_results['Counts - Issues'].get(severity, 0) + 1)
              }, recursive=True),
          'Hosts with Issues':
            overall_results['Hosts with Issues']
            | combine({
                severity: overall_results['Hosts with Issues'].get(severity, []) + [aggregated_host]
              }, recursive=True)
        }, recursive=True)
      }}
  loop: "{{ _host_issues.keys() | list }}"
  loop_control:
    loop_var: severity