---
- name: Start checks debug
  debug:
    msg: "Running do_checks role with checks: {{ checks_to_run | map(attribute='name') | list }}"


- name: Resolve selected groups into a list
  set_fact:
    selected_groups_normalized: >-
      {{
        (check_groups.keys() | list)
        if (selected_groups | default('ALL') | upper == 'ALL')
        else
          (
            selected_groups | split(',') | map('trim') | reject('equalto','') | list
          )
      }}

- name: DEBUG - Display selected groups
  debug:
    msg: "Selected groups to run: {{ selected_groups_normalized }}"

- name: Run selected groups
  include_tasks: run_checks_group.yml
  loop: "{{ selected_groups_normalized }}"
  loop_control:
    loop_var: group_name

- name: Display accumulated check results
  debug:
    msg:
      Flow: Upgrading from {{ axonius_version }} to {{ version | default('some version') }}
      Counts - Executed: "{{ executed_checks_count }}"
      Counts - Issues: >-
        {{
          dict(
            all_checks
            | dict2items
            | map(attribute='key')
            | zip(
                all_checks
                | dict2items
                | map(attribute='value')
                | map('length')
              )
          )
        }}
      Counts - Skipped: "{{ skipped_checks | length }}"
      Issues details: "{{ all_checks }}"
      Skipped: "{{ skipped_checks }}"





