---
- name: Initialize variables for {{ check.name }}
  run_once: true
  delegate_to: localhost
  set_fact:
    check_errors: null
    check_skipped: null
    check_unimplemented: null
    executed_checks_count: "{{ (executed_checks_count | int) + 1 }}"

- name: Run check {{ check.name }}
  include_tasks: "checks/{{ group_name }}/{{ check.name }}.yml"

- name: Accumulate skipped {{ check.name }}
  set_fact:
    skipped_checks: "{{ skipped_checks | ansible.builtin.combine({check.name: check_skipped}) }}"
  when:
    - check_skipped is not none

- name: Accumulate unimplemented {{ check.name }}
  set_fact:
    unimplemented_checks: "{{ unimplemented_checks | ansible.builtin.combine({check.name: check_unimplemented}) }}"
  when:
    - check_unimplemented is not none

- name: Route check output by severity
  set_fact:
    all_checks: >-
      {{
        all_checks
        | combine(
            { check.fail_strategy: (all_checks.get(check.fail_strategy, {}) | combine({check.name: check_errors})) },
            recursive=True
          )
      }}
  when: check_errors is not none
