---
- name: Initialize variables for {{ check.name }}
  set_fact:
    check_errors: ''
    check_details: {}
    check_skipped: null


- name: Run check {{ check.name }}
  include_tasks: "checks/{{ check.name }}.yml"


- name: Accumulate skipped {{ check.name }}
  set_fact:
    skipped_checks: "{{ skipped_checks | ansible.builtin.combine({check.name: check_skipped}) }}"
  when:
    - check_skipped is not none

- name: Route check output by severity
  set_fact:
    all_checks: >-
      {{
        all_checks
        | combine(
            { check.fail_strategy: (all_checks.get(check.fail_strategy, {}) | combine({check.name: check_errors})) },
            recursive=True
          )
      }}
  when: check_errors | length > 0
