---
# Variables for do_checks role

# Initialize accumulators for results

all_checks: {}
skipped_checks: {}


checks_to_run:
  - name: my_check_a
    fail_strategy: "ERROR"  # Options: "CRITICAL", "ERROR", "WARNING", "INFO"

  - name: my_check_b
    fail_strategy: "WARNING"