---
# Default variables for do_checks role

required_tools:
  - awk
  - grep
  - sed
  - cp
  - tar
  - docker

supported_os_distributions:
  ubuntu:
    - "24"
    - "22"
    - "20"
  rhel:
    - "9"
    - "8"
  rocky:
    - "9"
    - "8"

supported_docker_major_versions:
  - "28"
  - "27"
  - "26"
  - "25"
  - "23"
