---

- name: Skip disk space check if Docker host info is not available
  set_fact:
    check_skipped: "Docker host info is not available, disk space check skipped"
  when: docker_host_info.host_info is not defined

- name: Check disk space for Docker root path
  block:
  - name: Set Docker root path from host info
    ansible.builtin.set_fact:
      docker_root_path: "{{ docker_host_info.host_info.DockerRootDir }}"

  - name: Check if in forbidden directory - unimplemented
    set_fact:
        check_unimplemented: "Need help to understand what to check"

  when: docker_host_info.host_info is defined


