---

- name: Run check required tools module
  do_tools_exist:
    tool_list: "{{ required_tools }}"
  register: module_result


- name: Process upgrade path check details
  set_fact:
    check_details: "{{ module_result.check_details }}"
    check_errors: "{{ module_result.check_errors | default(none) }}"
