---

- name: Set error message if docker is not responsive
  set_fact:
    check_errors: >-
        Unable to retrieve host information. Docker is not responsive.
  when: docker_host_info.host_info is not defined

- name: Set check details for required tools
  set_fact:
    check_details:
      docker_host_info: "{{ docker_host_info }}"
  when: docker_host_info.host_info is defined
