---
- name: Get OS distribution
  ansible.builtin.set_fact:
    os_distribution: "{{ ansible_distribution | default('unknown') | lower }}"

- name: Get OS version
  ansible.builtin.set_fact:
    os_version: "{{ ansible_distribution_major_version | default('unknown') }}"

- name: Set check details for OS version
  set_fact:
    check_details:
      supported_distributions: "{{ supported_os_distributions }}"
      current_distribution: "{{ os_distribution }}"
      current_version: "{{ os_version }}"

- name: Set error message if OS version is not supported
  set_fact:
    check_errors: >-
      Unsupported OS distribution: {{ os_distribution }} {{ os_version }}.
  when: os_distribution not in supported_os_distributions

- name: Set error message if OS version is not supported
  set_fact:
    check_errors: >-
      Unsupported {{ os_distribution }} version: {{ os_version }}.
  when: os_distribution in supported_os_distributions and os_version not in supported_os_distributions[os_distribution]
