---

- name: Check if my_check_b should be skipped
  set_fact:
      check_skipped: "version is not defined, skipping my_check_b"
  when: version is not defined

- name: Execute my_check_b
  block:
  - name: Run my_check_b module
    my_check_b:
      param1: "value1"
      param2: "value2"
    register: module_result

  - name: Process my_check_b details
    set_fact:
      check_details: "{{ module_result.check_details }}"
      check_errors: "{{ module_result.check_errors | default(none) }}"
  when: version is defined
