---

- name: Run my_check_a dummy implementation
  debug:
    msg: "Running my_check_a with fail strategy {{ check.fail_strategy }}"

- name: Simulate my_check_a results
  set_fact:
    check_details: {"details": "my_check_a passed successfully!", "tool": "ansible"}

